In [2]:
import os
os.listdir()

['Testings.ipynb',
 '.DS_Store',
 'supermarkets.json',
 'supermarkets.csv',
 'supermarkets-semi-colons.txt',
 'supermarkets.xlsx',
 '.ipynb_checkpoints',
 'supermarkets-commas.txt']

In [3]:
import pandas

In [18]:
df1=pandas.read_csv("supermarkets.csv")
df1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [17]:
df2=pandas.read_excel('supermarkets.xlsx')
df2

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [19]:
df3=pandas.read_csv("http://pythonhow.com/supermarkets.csv")
df3

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [1]:
df4=pandas.read_csv("supermarkets-semi-colons.txt", sep=";")
df4.drop("Name",1)
df1["Address"]=df1["Address"]+", "+ df1["City"]+", "+ df1["State"]+", " +df1["Country"]
df1["Address"]

NameError: name 'pandas' is not defined

In [43]:
from geopy.geocoders import Nominatim
nom=Nominatim()

df1["Coordinates"]=df1["Address"].apply(nom.geocode)

df1["Longitude"]=df1["Coordinates"].apply(lambda x: x.longitude if x!=None else None)


In [45]:
df1["Latitude"]=df1["Coordinates"].apply(lambda x: x.latitude if x!=None else None)
df1

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates   Longitude   Latitude  
0  (3666, 21st Street, Noe Valley, SF, California... -122.429343  37.756489  
1                                               None         NaN        NaN  
2  (332, Hill Street, Noe Valley, SF, California,... -122.428601  37.755725  
3  (3995, 23rd Street, Noe Valley, SF, California... -122.431714  37.752965  
4  (1056, Sanchez Street, Noe Valley, SF, Califor... -122.429815  37.752146  
5  (551, Alvarado Street, Noe Valley, SF, Califor... -122.433220  37.753673

In [30]:
df1.Coordinates[5].latitude

37.7536733265306

In [33]:
import cv2

In [36]:
gray=cv2.imread("smallgray.png",0)
gray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [46]:
cv2.imwrite("newg.png",gray)

True

In [1]:
import numpy
n = numpy.arange(27)

In [3]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
m=numpy.asarray([[123,12,123,12,33],[],[]])
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [6]:
print(m)

[list([123, 12, 123, 12, 33]) list([]) list([])]


In [8]:
type(m)
import cv2

In [10]:
im_g=cv2.imread("smallgray.png",0)

In [11]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [12]:
im_g[0:2,2:3]

array([[104],
       [255]], dtype=uint8)

In [14]:
im_g[2,4]

182

In [17]:
## ITERATING THROUGH NUMPY ARRAYS

for i in im_g:
    print(i)

for i in im_g.T:
    print(i)
    
for i in im_g.flat:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]
[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]
187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [21]:
ims=numpy.hstack((im_g,im_g))
print(ims)
imv=numpy.vstack((im_g,im_g))
print(imv)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]
[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [27]:
lst=numpy.hsplit(imv,5)
print(lst)
lsv=numpy.vsplit(imv,3)
print(lsv)

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]
[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]
